### ISSUE TITLE
bug: broken webpack logo in README

### ISSUE THREAD

**Issue by snitin315** [webpack-ui/webpack-ui#29]
the logo is broken in README.md

![Screenshot from 2020-02-22 15-04-38](https://user-images.githubusercontent.com/46647141/75090034-cce7aa80-5584-11ea-9bd1-c24cc8f9bab9.png)

**Comment by davemarquess** [comment]
what browser are you seeing this in? just checked in Chrome, Firefox, Safari - displays as expected:

<img width="976" alt="Screen Shot 2020-02-22 at 1 48 34 PM" src="https://user-images.githubusercontent.com/33312483/75099754-37dfb400-557a-11ea-99e8-12220ec7dcb0.png">

**Comment by snitin315** [comment]
Working fine now in my browser(Chrome) as well. Hence Closing.
